### ISSUE TITLE
No map overlay

### ISSUE THREAD

**Issue by dingetje** [mpusz/GLKMaps#1]
I've downloaded and installed on my web server. When I open the map there's a nice google map, but no LKMAP overlay.

What am I doing wrong?

**Comment by mpusz** [comment]
It is nice to see that someone is interested in that project. If you will download all LKMAPS templates from LK homepage to the 'data' directory on your HTTP server everything will work fine.

Please mind that the project has just started and we still did not solve the problem of overlapping maps. We have some plans how to solve it, but no time to do that :-) If you have any ideas please share.

**Comment by dingetje** [comment]
I've placed a map template in the data folder, but it seems my PHP is too old (I have 4.4.4).
